version: '3.7'

services:
  orders_api:
    image: fiap-3soat-g15-orders-api:latest
    container_name: orders_api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - orders_db
    environment:
      - DB_ENDPOINT=orders_db:5432
      - DB_NAME=selforder
      - DB_USERNAME=selforder
      - DB_PASSWORD=self@Order123!
      - ADMIN_ACCESS_TOKEN=token
    ports:
      - "8080:8080"
    restart: always

  orders_db:
    image: postgres:15.4
    container_name: orders_db
    volumes:
      - stock_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=orders
      - POSTGRES_USER=selforder
      - POSTGRES_PASSWORD=self@Order123!
    ports:
      - "5434:5432"
    restart: always

volumes:
  orders_db:
    driver: local
