name: orders-api

services:
  orders_api:
    image: fiap-3soat-g15-orders-api:latest
    container_name: orders_api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      orders_db:
        condition: service_healthy
    environment:
      DB_ENDPOINT: orders_db:5432
      DB_NAME: orders
      DB_USERNAME: selforder
      DB_PASSWORD: self@Order123!
      STOCK_SERVICE_URL: http://localhost:8081
      PAYMENTS_SERVICE_URL: http://localhost:8082
    ports:
      - "8080:8080"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  orders_db:
    image: postgres:15.4
    container_name: orders_db
    volumes:
      - orders_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: selforder
      POSTGRES_PASSWORD: self@Order123!
    ports:
      - "5434:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  orders_db:
