spring:
  cloud:
    aws:
      endpoint: http://localhost:4566
      credentials:
        access-key: localstack
        secret-key: localstack
      region:
        static: ${AWS_REGION}
  application:
    name: orders-api
  datasource:
    url: jdbc:postgresql://${DB_ENDPOINT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    baseline-on-migrate: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
        jdbc:
          lob:
            non_contextual_creation: true
        ddl-auto: validate
        globally_quoted_identifiers: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_ygM5FRn7D
          jwk-set-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_ygM5FRn7D/.well-known/jwks.json

admin:
  access-token: ${ADMIN_ACCESS_TOKEN}

clients:
  stock-api:
    url: ${STOCK_SERVICE_URL}
  payments-api:
    url: ${PAYMENTS_SERVICE_URL}


topic:
  request-payment: arn:aws:sns:us-east-2:000000000000:request-payment_topic

sqs:
  queues:
    request-payment-response: payment-response_queue