spring:
  application:
    name: orders-api
  datasource:
    url: jdbc:postgresql://${DB_ENDPOINT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    baseline-on-migrate: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
        jdbc:
          lob:
            non_contextual_creation: true
        ddl-auto: validate
        globally_quoted_identifiers: true

clients:
  stock-api:
    url: ${STOCK_SERVICE_URL}
  payments-api:
    url: ${PAYMENTS_SERVICE_URL}

sqs:
  queues:
    request-payment-response: payment-response_queue

sns:
  topics:
    request-payment: request-payment_topic

security:
  enable: false